# Generated by Django 2.2.4 on 2019-08-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_modelwithfilefield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelWithFileField',
        ),
    ]
